### ISSUE TITLE
Reduce plugin size

### ISSUE THREAD

**Issue by distantnative** [distantnative/kirby-retour#15]
So much overload (e.g. moment.js in chart.js)

**Comment by sylvainjule** [comment]
The plugin seems very promising! Thanks a lot.
This issue looks familiar :) 

Threw some uglification in your package.json (844ko > 333ko)

```bash
npm i -D uglify-js
```

`package.json`
```
(...)
"build": "browserify -p [ vueify/plugins/extract-css -o index.css ] -p bundle-collapser/plugin -e src/main.js | uglifyjs -c warnings=false -m > index.js"
(...)
```

Then to ditch the moment.js bundled with chartjs (333ko -> 280ko):

```bash
npm i -D babel-plugin-module-resolver
```

Then in your .babelrc

```json
"plugins": [
    ["module-resolver", {
      "alias": {
        "chart.js": "chart.js/dist/Chart.min.js",
      }
    }]
]
```

**Comment by distantnative** [comment]
Thanks a lot! Worked like a charme: 844kb > 280kb. Will see later if there is more potential but this for sure helped a lot already. Added to upcoming 1.0.0-beta.2.
✅
