### ISSUE TITLE
Redirect 403/404 error

### ISSUE THREAD

**Issue by judbd** [distantnative/kirby-retour#36]
Hello, thank you for this plugin.

For now, kirby redirect all errors (4XX I gess) to the error page, but you can't tell if it's a 404 or 403 error for example, and show a message accordingly.

I don't know if it's in the plugin scope nor possible, but it will be cool if we can redirect to some page when some error codes are used.

**Comment by distantnative** [comment]
Ok, I got it locally working to specify e.g. 403 and get the error page with that code transmitted. In theory, you could also define a different page than the error page. Thinking even of an option to not deliver any kind of error page at all but let the browser fail.

What the plugin probably will not be able to do in the near future is to define error pages in general for different HTTP codes. Only setup a specific url/route and then define a http status code and a target location.
